[package]
name = "smarthome"
version = "0.1.0"
edition = "2021"
exclude = ["/tests"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsmarthome = { version = "0.1.0", path = "../libsmarthome" }
